name: funflutter_wandroid
description: 2.x && null-safety && getX

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

# 开启自动生成json
flutter-json:
  enable:true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  # 基础依赖
  package_info: ^2.0.0
  device_info: ^2.0.1
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  share: ^2.0.1
  hive: ^2.0.4
  logging: ^1.0.1
  date_format: ^2.0.2

  get:
  flutter_hooks:
  dio:

  bot_toast: ^4.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/animations/
    - assets/images/

  uses-material-design: true
